# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ai/h2o/audit/v1/event.proto, ai/h2o/audit/v1/event_service.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import List, Optional

import betterproto
import grpclib


@dataclass
class Event(betterproto.Message):
    """
    An audit event that records who performed what action and when. Used for
    tracking and auditing user activity across services.
    """

    # The resource name of the event. Format: `events/{event}`
    name: str = betterproto.string_field(1)
    # The user who performed the action. Format: `users/{user}`
    user: str = betterproto.string_field(2)
    # The source where the action originated (e.g., "animal-classifier").
    source: str = betterproto.string_field(3)
    # The action that was performed (e.g., "classify").
    action: str = betterproto.string_field(4)
    # How long the operation took to complete.
    execution_duration: timedelta = betterproto.message_field(5)
    # The time when the event was recorded.
    create_time: datetime = betterproto.message_field(6)


@dataclass
class CreateEventRequest(betterproto.Message):
    """Request message for CreateEvent."""

    # The event to create.
    event: "Event" = betterproto.message_field(1)


@dataclass
class CreateEventResponse(betterproto.Message):
    """Response message for CreateEvent."""

    # The created event.
    event: "Event" = betterproto.message_field(1)


@dataclass
class ListEventsRequest(betterproto.Message):
    """Request message for ListEvents."""

    # The maximum number of events to return.
    page_size: int = betterproto.int32_field(1)
    # A page token, received from a previous `ListEvents` call.
    page_token: str = betterproto.string_field(2)


@dataclass
class ListEventsResponse(betterproto.Message):
    """Response message for ListEvents."""

    # The list of events.
    events: List["Event"] = betterproto.message_field(1)
    # A token to retrieve the next page of results.
    next_page_token: str = betterproto.string_field(2)


class EventServiceStub(betterproto.ServiceStub):
    """Service for tracking audit events."""

    async def create_event(
        self, *, event: Optional["Event"] = None
    ) -> CreateEventResponse:
        """Creates a new audit event."""

        request = CreateEventRequest()
        if event is not None:
            request.event = event

        return await self._unary_unary(
            "/ai.h2o.audit.v1.EventService/CreateEvent",
            request,
            CreateEventResponse,
        )

    async def list_events(
        self, *, page_size: int = 0, page_token: str = ""
    ) -> ListEventsResponse:
        """Lists audit events."""

        request = ListEventsRequest()
        request.page_size = page_size
        request.page_token = page_token

        return await self._unary_unary(
            "/ai.h2o.audit.v1.EventService/ListEvents",
            request,
            ListEventsResponse,
        )
